title: "Jason Eubank"
name: "Jason Eubank"
logo: /assets/img/Eubank, Jason_Patient Accounts.jpg
description: "Data Analyst | Statistical Modeling | Sports Analytics"
show_downloads: false

remote_theme: sproogen/modern-resume-theme

# Personal Links
email: jjeubank2@icloud.com
github_username: jeubank2-x
linkedin_username: 
resume_download: false

# Build Settings
markdown: kramdown

# Website Sections
education:
  - degree: "B.S. Computational Mathematics"
    university: "Liberty University"
    dates: "Graduating Aug 2025"

experience:
  - role: "Payment Analyst"
    company: "University of North Carolina Chapel Hill"
    dates: "May 2024 - Present"
    details:
      - "Analyze and investigate payment and account data trends to resolve discrepancies and improve revenue accuracy."
      - "Created and optimized workflows that reduced processing delays and improved financial data integrity."

projects:
  - title: "Analyzing the Influence of NBA Scheduling"
    description: "Assessment of how schedule structure and travel impact performance and win probability."
    link: "#"
    tools: "R, Dplyr, Tidyr, Purrr, Stats, GGplot2"

  - title: "MLB Player Performance Prediction Model"
    description: "Predictive model estimating likelihood of hits and HR outcomes using matchup, stadium, and historical data."
    link: "#"
    tools: "R, Dplyr, Tidyr, Stats"
