#Site
title: "Jason Eubank"
name: "Jason Eubank"
logo: /assets/img/Eubank, Jason_Patient Accounts.jpg
description: "Data Analyst | Statistical Modeling | Sports Analytics"

remote_theme: sproogen/modern-resume-theme

# Personal Links
email: jjeubank2@icloud.com
github_username: jeubank2-x
linkedin_username: 
resume_download: false

# Build Settings
markdown: kramdown

